[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false
seeds = true

[programs.localnet]
counter = "HpjTvLKu963kUo3LcxKNmFVYgBHDMGgxyDWV3ZHPNZv2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""

[programs.devnet]
counter = "HpjTvLKu963kUo3LcxKNmFVYgBHDMGgxyDWV3ZHPNZv2"